<?php
// PASTA PARA TODAS AS FUNÇÕES QUE NÃO TEM LUGAR ESPECIFICO OU VOU REUTILIZAR DURANTE O CODIGO

// DIZ ONDE É A RAIZ DO SISTEMA PARA QUE POSSA SER LINKADO AS IMG E ESTILOS
$BASE_URL = "http://" . $_SERVER["SERVER_NAME"] . dirname($_SERVER['REQUEST_URI'] . '?') . '/';


?>